// FAKE DATA

export const books = [
    {
      id: 1,
      title: "Ponyo",
      url: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
      originalPrice: 49.95,
      salePrice: 14.95,
      rating: 4.5,
    },
    {
      id: 2,
      title: "Porco Rosso",
      url: "https://covers.openlibrary.org/b/id/10958382-L.jpg",
      originalPrice: 39,
      salePrice: null,
      rating: 5,
    },
    {
      id: 3,
      title: "Grave Of The Fireflies",
      url: "https://covers.openlibrary.org/b/id/10425061-L.jpg",
      originalPrice: 29,
      salePrice: null,
      rating: 5,
    },
    {
      id: 4,
      title: "When Marnie Was There",
      url: "https://covers.openlibrary.org/b/id/10088428-L.jpg",
      originalPrice: 44,
      salePrice: 19,
      rating: 4.5,
    },
    {
      id: 5,
      title: "Whisper Of The Heart",
      url: "https://covers.openlibrary.org/b/id/9978588-L.jpg",
      originalPrice: 32,
      salePrice: null,
      rating: 5,
    },
    {
      id: 6,
      title: "Spirited Away",
      url: "https://covers.openlibrary.org/b/id/7737110-L.jpg",
      originalPrice: 70,
      salePrice: 12.5,
      rating: 5,
    },
    {
      id: 7,
      title: "Kiki's Delivery Service",
      url: "https://covers.openlibrary.org/b/id/2380224-L.jpg",
      originalPrice: 11,
      salePrice: 10,
      rating: 4,
    },
    {
      id: 8,
      title: "Princess Mononoke",
      url: "https://covers.openlibrary.org/b/id/1954899-L.jpg",
      originalPrice: 38,
      salePrice: 17.95,
      rating: 4.5,
    },
    {
      id: 9,
      title: "Nausicaä Of The Valley Of The Wind",
      url: "https://covers.openlibrary.org/b/id/8906626-L.jpg",
      originalPrice: 35,
      salePrice: 19.95,
      rating: 4.5,
    },
    {
      id: 10,
      title: "Only Yesterday",
      url: "https://covers.openlibrary.org/b/id/8114155-L.jpg",
      originalPrice: 40,
      salePrice: null,
      rating: 5,
    },
    {
      id: 11,
      title: "The Cat Returns",
      url: "https://covers.openlibrary.org/b/id/7895280-L.jpg",
      originalPrice: 30,
      salePrice: 20,
      rating: 5,
    },
    {
      id: 12,
      title: "My Neighbor Totoro",
      url: "https://covers.openlibrary.org/b/id/8479576-L.jpg",
      originalPrice: 30,
      salePrice: 12.95,
      rating: 4.5,
    },
  ];